### ISSUE TITLE
Slow Block Times, this is a scam

### ISSUE THREAD

**Issue by oojr** [Bitcoin-Clashic/bitcoin-clashic#2]
seems like a scam,

**Comment by cryptomeow** [comment]
Not a scam, this is the True Vision of Satoshi.

Regarding the block timed, EDA is now in effect, the last block was mined with 20% reduced difficulty (417970802839.394). It'll be getting better now. You can help by mining (the first pool to launch is http://pool.bclashic.network:5964/ )

Soon it'll be back on track towards the vision.
